import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={` text-center`}>
          <h1 className=" text-blue-300 text-3xl">Map Tripper</h1>
          <p className="mt-3 text-blue-100 text-base">
            Use Airtable or Notion to render your next getaway
          </p>
        </div>
      </main>
    </>
  );
}
